#!/bin/sh
set -eu

echo "---------- Git hook: pre-commit ----------"

# Biome (lint and format)
echo ">>> [1/2] Running Biome"
yarn biome:check

# Typechecking
echo ">>> [2/2] Compiling Typescript"
yarn tsc

echo "------------------------------------------"
