version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      production:
        dependency-type: "production"
      development:
        dependency-type: "development"
    # Utils
    reviewers:
      - "Jordan-Kowal"
    commit-message:
      prefix: "[Deps] "
