version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    groups:
      all:
        patterns: ["*"]
    reviewers:
      - "Jordan-Kowal"
    commit-message:
      prefix: "[Deps] "
