extends:
  - airbnb
  - react-app
  - plugin:jsx-a11y/recommended
  - prettier
rules:
  no-plusplus: [2, { allowForLoopAfterthoughts: true }]
  camelcase: ['error', { ignoreDestructuring: true }]
  no-use-before-define: ['error', { functions: false, classes: false }]
  arrow-body-style: ['error', 'as-needed']
  jsx-a11y/label-has-associated-control: [2, { depth: 3 }]
  react/jsx-filename-extension: [1, { extensions: ['.js'] }]
  react/jsx-one-expression-per-line: 0
  react/jsx-curly-newline: 0
  react/require-default-props: ['error', { ignoreFunctionalComponents: true }]
  react/jsx-props-no-spreading: 2
  import/no-unresolved: 0
  react-hooks/exhaustive-deps: ['warn', { 'additionalHooks': '(useWebSocket)' }]
  react/function-component-definition: 0
  default-param-last: 0
  react/no-unstable-nested-components: 1
  prefer-promise-reject-errors: 0
  jsx-a11y/click-events-have-key-events: 0
  jsx-a11y/no-static-element-interactions: 0

overrides:
  - files:
      - '**/index.js'
    rules:
      import/prefer-default-export: 0
      no-restricted-exports: 0
  - files:
      - '**/*.test.js'
      - '**/*.spec.js'
      - '**/__tests__/*.js'
    rules:
      react/jsx-props-no-spreading: 0
    settings:
      disable/plugins: ['jsx-a11y']
  - files:
      - '**/*.stories.js'
      - '**/*story.js'
    rules:
      react/jsx-props-no-spreading: 0
      react/prop-types: 0
      no-alert: 0
