name: QA

on:
  workflow_dispatch:
  pull_request:
    branches: ['main']

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'  # Cached by github (https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#nodejs)
          cache: 'yarn'
          cache-dependency-path: ./yarn.lock

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.yarn
            ./node_modules
          key: yarn-${{ hashFiles('./yarn.lock') }}

      - name: Install dependencies
        if: ${{ steps.cache-dependencies.outputs.cache-hit != 'true' }}
        run: yarn install

  biome:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.yarn
            ./node_modules
          key: yarn-${{ hashFiles('./frontend/yarn.lock') }}

      - name: Run biome
        run: yarn biome:check

  tests:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.yarn
            ./node_modules
          key: yarn-${{ hashFiles('./yarn.lock') }}

      - name: Run tests
        run: yarn test
