name: QA

on:
  pull_request:
    branches: ['master']
  push:
    branches: ['master']

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Run pre-commits
        run: pre-commit run --all-files

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 19.6.0
        uses: actions/setup-node@v3
        with:
          node-version: '19.6.0'
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
